### ISSUE TITLE
Add drag & drop capabilities

### ISSUE THREAD

**Issue by pierotofy** [uav4geo/Thermal-Tools#2]
Could be nice to add the ability to drag & drop a folder (or files?) instead of manually selecting it.

**Comment by diegoaces** [comment]
Hello Piero, do you need the app to do something like this?

https://github.com/diegoaces/flutter-GeoTag-Mapper/blob/main/gif/example.gif

**Comment by pierotofy** [comment]
Something like that, yes. 👍

**Comment by diegoaces** [comment]
Preview:  
<img width="1089" alt="Captura de pantalla 2024-07-13 a la(s) 2 39 18 p  m" src="https://github.com/user-attachments/assets/9f2a154e-73c4-4a82-b723-a0e243b2f60e">
